#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path: /authentication_token
    methods: ['POST']
index:
    path: /payment_intent
    methods: ['POST']
    controller: App\Controller\PaymentIntentController